export const CATALOG = [
  {
    category: 'AC & Appliance Repair', icon: '❄️', color: '#E0F2FE',
    services: [
      {
        name: 'AC Service & Maintenance',
        description: 'Routine servicing of split or window AC unit including foam-jet cleaning, filter wash, coil cleaning and performance check.',
        variants: ['Split AC', 'Window AC', 'Cassette AC'],
        priceRange: [599, 899],
        addons: [{ name: 'Deep filter cleaning', price: 150 }, { name: 'Coil sanitisation', price: 200 }, { name: 'PCB inspection', price: 300 }],
      },
      {
        name: 'AC Repair',
        description: 'Diagnosis and repair of AC faults such as compressor failure, PCB issues, fan motor fault, or refrigerant leaks causing no cooling.',
        variants: ['Compressor fault', 'PCB fault', 'Fan motor fault', 'Noise / vibration'],
        priceRange: [399, 4500],
        addons: [{ name: 'Compressor replacement', price: 3500 }, { name: 'PCB replacement', price: 2500 }, { name: 'Fan motor replacement', price: 1200 }, { name: 'Capacitor replacement', price: 400 }],
      },
      {
        name: 'AC Gas Refill',
        description: 'Refilling refrigerant gas in AC units that are not cooling due to low gas levels or a slow leak.',
        variants: ['R22 gas', 'R32 gas', 'R410A gas'],
        priceRange: [2200, 3500],
        addons: [{ name: 'Leak detection & sealing', price: 500 }, { name: 'Extra 100g gas', price: 400 }],
      },
      {
        name: 'AC Installation & Uninstallation',
        description: 'Professional installation of a new split or window AC unit, or uninstallation of an existing unit for shifting or replacement.',
        variants: ['Split AC installation', 'Window AC installation', 'Split AC uninstallation', 'Relocation (uninstall + reinstall)'],
        priceRange: [999, 2499],
        addons: [{ name: 'Copper pipe per foot', price: 120 }, { name: 'Wall brackets', price: 350 }, { name: 'Stabiliser installation', price: 249 }],
      },
      {
        name: 'Washing Machine Repair',
        description: 'Repair of front-load or top-load washing machines with issues like not spinning, not draining, drum noise, or display errors.',
        variants: ['Front-load', 'Top-load semi-automatic', 'Top-load fully automatic'],
        priceRange: [299, 2500],
        addons: [{ name: 'Drum bearing replacement', price: 800 }, { name: 'Motor replacement', price: 1800 }, { name: 'PCB replacement', price: 1500 }],
      },
      {
        name: 'Refrigerator Repair',
        description: 'Diagnosis and repair of fridge issues like not cooling, compressor noise, ice maker fault, water dispenser leak, or thermostat failure.',
        variants: ['Single door', 'Double door', 'Side-by-side', 'Mini fridge'],
        priceRange: [349, 3500],
        addons: [{ name: 'Compressor replacement', price: 2800 }, { name: 'Gas refill', price: 1200 }, { name: 'Thermostat replacement', price: 600 }],
      },
      {
        name: 'Microwave Repair',
        description: 'Repair of microwave ovens that are not heating, sparking, turntable not rotating, or display not working.',
        variants: ['Solo microwave', 'Grill microwave', 'Convection microwave'],
        priceRange: [249, 1800],
        addons: [{ name: 'Magnetron replacement', price: 1200 }, { name: 'Door switch replacement', price: 400 }, { name: 'Turntable motor', price: 350 }],
      },
      {
        name: 'Dishwasher Repair',
        description: 'Repair of dishwashers not cleaning properly, not draining, door latch fault, or water inlet issues.',
        variants: ['Freestanding dishwasher', 'Built-in dishwasher'],
        priceRange: [399, 2800],
        addons: [{ name: 'Pump motor replacement', price: 1500 }, { name: 'Spray arm replacement', price: 600 }, { name: 'Control panel repair', price: 900 }],
      },
    ],
  },

  {
    category: 'Geyser & Water Heater', icon: '🚿', color: '#FEE2E2',
    services: [
      {
        name: 'Geyser Service',
        description: 'Deep cleaning and descaling of electric geyser including exterior cleaning, anode rod check, and performance optimisation.',
        variants: ['Storage geyser (electric)', 'Instant geyser (electric)'],
        priceRange: [599, 799],
        addons: [{ name: 'Anode rod replacement', price: 350 }, { name: 'Thermostat check', price: 150 }],
      },
      {
        name: 'Geyser Repair',
        description: 'Fixing geyser issues like not heating, tripping MCB, leaking from body or connections, or thermostat failure.',
        variants: ['Not heating', 'Leaking', 'MCB tripping', 'Thermostat fault'],
        priceRange: [249, 1800],
        addons: [{ name: 'Heating element replacement', price: 700 }, { name: 'Thermostat replacement', price: 500 }, { name: 'Pressure relief valve', price: 300 }],
      },
      {
        name: 'Geyser Installation',
        description: 'Installation of a new electric geyser with all plumbing connections, safety valve fitting and testing.',
        variants: ['Wall-mounted storage geyser', 'Instant geyser', 'Vertical geyser'],
        priceRange: [499, 799],
        addons: [{ name: 'Additional pipe fittings', price: 200 }, { name: 'Safety valve', price: 150 }],
      },
    ],
  },

  {
    category: 'Plumbing', icon: '🔧', color: '#FEF3C7',
    services: [
      {
        name: 'Tap / Faucet Repair',
        description: 'Fixing dripping taps, loose faucets, seized handles, or replacing worn washers and O-rings in kitchen or bathroom taps.',
        variants: ['Kitchen tap', 'Bathroom tap', 'Mixer faucet', 'Pillar cock'],
        priceRange: [199, 750],
        addons: [{ name: 'Tap replacement (basic)', price: 350 }, { name: 'Tap replacement (premium)', price: 800 }, { name: 'Sealant & fittings', price: 150 }],
      },
      {
        name: 'Pipe Repair & Leakage Fix',
        description: 'Repairing burst or leaking pipes under the sink, in walls, or overhead plumbing that causes water damage or dampness.',
        variants: ['Under-sink pipe', 'Wall-embedded pipe', 'Overhead pipe', 'Bathroom connection pipe'],
        priceRange: [499, 1800],
        addons: [{ name: 'PVC pipe per foot', price: 80 }, { name: 'Wall opening & closing', price: 600 }, { name: 'Emergency surcharge', price: 250 }],
      },
      {
        name: 'Drain Unclogging',
        description: 'Clearing blocked kitchen drains, bathroom drains, or toilet blockages using plunging, snaking, or chemical jetting.',
        variants: ['Kitchen drain', 'Bathroom floor drain', 'Wash basin drain', 'Toilet blockage'],
        priceRange: [299, 1100],
        addons: [{ name: 'Chemical jetting', price: 400 }, { name: 'CCTV pipe inspection', price: 800 }],
      },
      {
        name: 'Toilet Repair',
        description: 'Fixing continuously running toilets, flush tank issues, broken flush valve, slow fill, or toilet seat replacement.',
        variants: ['Flush tank running water', 'Flush valve replacement', 'Low flush pressure', 'Toilet seat replacement'],
        priceRange: [149, 1200],
        addons: [{ name: 'Flush valve kit', price: 350 }, { name: 'Fill valve replacement', price: 280 }, { name: 'Toilet seat (basic)', price: 600 }],
      },
      {
        name: 'Bathroom Fitting Installation',
        description: 'Installation of new bathroom fixtures including showers, hand showers, concealed flush tanks, towel holders, and soap dispensers.',
        variants: ['Shower head', 'Hand shower set', 'Concealed flush tank', 'Health faucet / bib cock'],
        priceRange: [299, 1500],
        addons: [{ name: 'Concealed piping', price: 500 }, { name: 'Anti-scalding valve', price: 400 }],
      },
      {
        name: 'Water Tank Cleaning',
        description: 'Cleaning and disinfecting overhead or underground water storage tanks to remove sludge, algae and bacterial buildup.',
        variants: ['Overhead tank (up to 500L)', 'Overhead tank (500–1000L)', 'Underground sump (up to 2000L)'],
        priceRange: [799, 2999],
        addons: [{ name: 'Anti-bacterial disinfection', price: 300 }, { name: 'Tank inspection report', price: 200 }],
      },
      {
        name: 'Water Purifier Service',
        description: 'Routine servicing and filter replacement for RO, UV, or UF water purifiers to restore water quality and flow rate.',
        variants: ['RO system', 'UV system', 'RO + UV + UF combo'],
        priceRange: [399, 1499],
        addons: [{ name: 'Sediment filter replacement', price: 300 }, { name: 'RO membrane replacement', price: 900 }, { name: 'Carbon filter', price: 250 }],
      },
    ],
  },

  {
    category: 'Electrician', icon: '⚡', color: '#FFFBEB',
    services: [
      {
        name: 'Electrical Fault Diagnosis & Repair',
        description: 'Identifying and fixing electrical faults like short circuits, tripping MCBs, sparking sockets, or dead power points.',
        variants: ['Short circuit', 'Tripping MCB / fuse', 'Sparking socket / switch', 'Dead power point'],
        priceRange: [249, 1200],
        addons: [{ name: 'Wiring replacement per metre', price: 60 }, { name: 'MCB replacement', price: 350 }, { name: 'Emergency surcharge', price: 200 }],
      },
      {
        name: 'Fan Installation & Repair',
        description: 'Installing new ceiling fans, repairing fans that are not starting, making noise, rotating slowly, or have capacitor issues.',
        variants: ['Ceiling fan installation', 'Ceiling fan repair', 'Exhaust fan installation', 'Table / pedestal fan repair'],
        priceRange: [149, 799],
        addons: [{ name: 'Capacitor replacement', price: 150 }, { name: 'Fan regulator', price: 200 }, { name: 'Extra wiring 5m', price: 200 }],
      },
      {
        name: 'Light Fitting & Switch Installation',
        description: 'Installing new light fixtures, LED panels, chandeliers, switches, or sockets; replacing faulty switchboards.',
        variants: ['LED fitting', 'Chandelier / decorative light', 'Switch replacement', 'Socket / power point', 'Switchboard replacement'],
        priceRange: [99, 599],
        addons: [{ name: 'Conduit & casing', price: 150 }, { name: 'Extra wiring 5m', price: 200 }, { name: 'LED batten fitting', price: 250 }],
      },
      {
        name: 'Geyser / Water Heater Electrical Work',
        description: 'Electrical wiring and connection for geyser or water heater installation, including dedicated circuit and safety earthing.',
        variants: ['New geyser wiring', 'Existing geyser rewiring', 'ELCB / safety switch installation'],
        priceRange: [299, 799],
        addons: [{ name: 'ELCB installation', price: 400 }, { name: 'MCB addition', price: 250 }],
      },
      {
        name: 'Home Wiring & Rewiring',
        description: 'Complete or partial rewiring of rooms, laying conduit, extending circuits for new appliances or renovation work.',
        variants: ['Single room rewiring', 'Kitchen circuit extension', 'New circuit for AC', 'Full apartment rewiring'],
        priceRange: [999, 8999],
        addons: [{ name: 'Conduit per metre', price: 80 }, { name: 'Distribution board upgrade', price: 1500 }],
      },
      {
        name: 'Doorbell & Intercom Installation',
        description: 'Installing new doorbells, wireless chimes, or video intercom systems at the main door.',
        variants: ['Wired doorbell', 'Wireless doorbell', 'Video intercom'],
        priceRange: [149, 999],
        addons: [{ name: 'Extra wiring', price: 150 }, { name: 'Additional chime unit', price: 300 }],
      },
      {
        name: 'CCTV & Smart Device Installation',
        description: 'Installing CCTV cameras, smart home switches, smart plugs, or home automation devices with wiring and configuration.',
        variants: ['CCTV camera (per camera)', 'Smart switch installation', 'Smart plug setup', 'DVR/NVR installation'],
        priceRange: [299, 2999],
        addons: [{ name: 'Cable trunking per metre', price: 60 }, { name: 'Mounting bracket', price: 150 }],
      },
    ],
  },

  {
    category: 'Carpentry', icon: '🪚', color: '#FEF9C3',
    services: [
      {
        name: 'Furniture Repair',
        description: 'Repairing broken beds, chairs, tables, wooden sofas, or loose joints in household furniture.',
        variants: ['Bed support / slat repair', 'Wooden chair repair', 'Dining table repair', 'Wooden sofa repair', 'Headboard repair'],
        priceRange: [49, 799],
        addons: [{ name: 'Wood filler & polish touch-up', price: 150 }, { name: 'Replacement hardware', price: 100 }],
      },
      {
        name: 'Door Repair & Installation',
        description: 'Repairing stuck, warped, or damaged wooden doors; fixing door hinges, closers, or installing new interior doors.',
        variants: ['Door alignment fix (sticking / dragging)', 'Hinge replacement', 'Door closer installation', 'New door installation', 'Door frame repair'],
        priceRange: [199, 1500],
        addons: [{ name: 'Door polish', price: 400 }, { name: 'Weather strip', price: 200 }],
      },
      {
        name: 'Door Lock & Security Fitting',
        description: 'Repairing or replacing door locks, deadbolts, knobs, digital locks, or fitting security chains and door viewers.',
        variants: ['Mortise lock repair', 'Digital / smart lock installation', 'Door knob replacement', 'Security chain fitting', 'Peephole installation'],
        priceRange: [129, 1999],
        addons: [{ name: 'Digital lock (basic)', price: 2500 }, { name: 'Extra keys cutting', price: 150 }],
      },
      {
        name: 'Cupboard & Cabinet Repair',
        description: 'Fixing broken cupboard shutters, drawer slides, cabinet hinges, hydraulic channels, or wardrobe alignment issues.',
        variants: ['Cupboard shutter alignment', 'Drawer slide replacement', 'Cabinet hinge repair', 'Hydraulic channel replacement', 'Wardrobe lock repair'],
        priceRange: [79, 599],
        addons: [{ name: 'Soft-close hinge upgrade', price: 200 }, { name: 'Anti-rust treatment', price: 150 }],
      },
      {
        name: 'Shelf & Storage Installation',
        description: 'Installing wall-mounted shelves, floating shelves, kitchen racks, book shelves, or utility storage units.',
        variants: ['Wall shelf (per shelf)', 'Floating shelf set', 'Kitchen wall rack', 'Bathroom shelf', 'Study room shelving'],
        priceRange: [99, 999],
        addons: [{ name: 'Wall plugs & anchors', price: 80 }, { name: 'Shelf brackets (pair)', price: 120 }],
      },
      {
        name: 'Curtain Rod & Blind Installation',
        description: 'Fitting curtain rods, tracks, roller blinds, or venetian blinds in living rooms, bedrooms or bathrooms.',
        variants: ['Curtain rod (per window)', 'Curtain track system', 'Roller blind', 'Venetian blind', 'Blackout blind'],
        priceRange: [149, 799],
        addons: [{ name: 'Wall drilling (hard surface)', price: 100 }, { name: 'Extra ceiling bracket', price: 80 }],
      },
      {
        name: 'Mirror & Decor Installation',
        description: 'Safely mounting large mirrors, wall art, frames, and decorative items with proper anchoring to avoid damage.',
        variants: ['Large mirror (above 3 ft)', 'Small mirror', 'Wall art / frame', 'Bathroom mirror cabinet', 'TV unit mounting'],
        priceRange: [79, 799],
        addons: [{ name: 'Anti-tilt safety kit', price: 150 }, { name: 'Cable management', price: 100 }],
      },
      {
        name: 'Window Repair & Mosquito Net',
        description: 'Repairing jammed, misaligned, or damaged windows; installing mosquito mesh nets or window screens.',
        variants: ['Window alignment fix', 'Window latch replacement', 'Mosquito net (per window)', 'Window mesh replacement'],
        priceRange: [89, 599],
        addons: [{ name: 'Heavy-duty mesh', price: 100 }, { name: 'Magnetic frame net', price: 350 }],
      },
      {
        name: 'Full-Day Carpenter Booking',
        description: 'Book a skilled carpenter for a full 8-hour day for custom woodwork, furniture assembly, modular installation, or renovation tasks.',
        variants: ['8-hour day booking', '4-hour half-day booking'],
        priceRange: [1999, 3499],
        addons: [{ name: 'Material procurement (per item)', price: 0 }, { name: 'Weekend surcharge', price: 300 }],
      },
    ],
  },

  {
    category: 'Cleaning', icon: '🧹', color: '#F0FDF4',
    services: [
      {
        name: 'Full Home Deep Clean',
        description: 'Professional deep cleaning of the entire apartment or house including rooms, kitchen, bathrooms, and balcony with machine floor scrubbing.',
        variants: ['Furnished 1 BHK', 'Furnished 2 BHK', 'Furnished 3 BHK', 'Furnished 4 BHK', 'Unfurnished apartment'],
        priceRange: [3199, 7999],
        addons: [{ name: 'Balcony cleaning', price: 300 }, { name: 'Window panel cleaning', price: 150 }, { name: 'Anti-bacterial spray', price: 250 }],
      },
      {
        name: 'Kitchen Deep Clean',
        description: 'Intensive cleaning of the kitchen including stove, countertops, tiles, sink, and cabinet exteriors with degreasing.',
        variants: ['Basic kitchen', 'Modular kitchen (with chimney)', 'Full modular kitchen + hob clean'],
        priceRange: [699, 1799],
        addons: [{ name: 'Chimney deep clean', price: 400 }, { name: 'Cabinet interior wipe', price: 200 }, { name: 'Refrigerator exterior', price: 150 }],
      },
      {
        name: 'Bathroom Deep Clean',
        description: 'Thorough cleaning of bathroom tiles, toilet bowl, washbasin, shower, mirrors, and exhaust fan with disinfection.',
        variants: ['Single bathroom', '2 bathrooms', '3+ bathrooms'],
        priceRange: [449, 1499],
        addons: [{ name: 'Grout scrubbing', price: 150 }, { name: 'Exhaust fan cleaning', price: 100 }, { name: 'Disinfectant treatment', price: 150 }],
      },
      {
        name: 'Sofa Cleaning',
        description: 'Steam or dry cleaning of fabric sofas to remove dust, stains, odours, and allergens using professional equipment.',
        variants: ['2-seater sofa', '3-seater sofa', 'L-shaped sofa', 'Recliner sofa (per seat)'],
        priceRange: [499, 2499],
        addons: [{ name: 'Stain treatment', price: 300 }, { name: 'Anti-bacterial spray', price: 200 }, { name: 'Deodorising treatment', price: 150 }],
      },
      {
        name: 'Carpet & Rug Cleaning',
        description: 'Extraction cleaning of carpets and rugs to remove embedded dirt, stains, pet hair, and allergens.',
        variants: ['Small rug (up to 4×6 ft)', 'Medium carpet (up to 6×9 ft)', 'Large carpet (above 9×12 ft)', 'Per sq ft rate'],
        priceRange: [349, 1999],
        addons: [{ name: 'Stain pre-treatment', price: 250 }, { name: 'Anti-static spray', price: 150 }],
      },
      {
        name: 'Chimney Cleaning',
        description: 'Deep cleaning of kitchen chimney filters, motor, and body to restore suction power and eliminate grease buildup.',
        variants: ['Auto-clean chimney', 'Filterless chimney', 'Baffle filter chimney', 'Mesh filter chimney'],
        priceRange: [399, 799],
        addons: [{ name: 'Filter replacement', price: 400 }, { name: 'Motor servicing', price: 250 }],
      },
      {
        name: 'Refrigerator Deep Clean',
        description: 'Thorough cleaning of fridge interior, shelves, drawers, and exterior, including deodorising and drip tray cleaning.',
        variants: ['Single door', 'Double door', 'Side-by-side'],
        priceRange: [349, 699],
        addons: [{ name: 'Deodorising sachets', price: 100 }, { name: 'Gasket cleaning & conditioning', price: 150 }],
      },
      {
        name: 'Mattress Deep Clean',
        description: 'Vacuuming, steam sanitisation, and deodorising of mattresses to eliminate dust mites, allergens, and sweat odours.',
        variants: ['Single mattress', 'Double mattress', 'Queen mattress', 'King mattress'],
        priceRange: [449, 1299],
        addons: [{ name: 'Anti-allergen treatment', price: 250 }, { name: 'Stain spot treatment', price: 200 }],
      },
      {
        name: 'Office & Commercial Cleaning',
        description: 'Deep cleaning of office spaces, co-working areas, or commercial premises including floors, desks, pantry, and restrooms.',
        variants: ['Up to 500 sq ft', '500–1000 sq ft', '1000–2000 sq ft'],
        priceRange: [2499, 9999],
        addons: [{ name: 'Pantry deep clean', price: 500 }, { name: 'Window cleaning', price: 300 }, { name: 'Disinfection fogging', price: 800 }],
      },
      {
        name: 'Post-Renovation / Move-In Clean',
        description: 'Removing construction dust, debris, and paint smears from a newly renovated or freshly moved-in home.',
        variants: ['1 BHK', '2 BHK', '3 BHK', '4 BHK'],
        priceRange: [2999, 9999],
        addons: [{ name: 'Window & glass polish', price: 400 }, { name: 'Floor tile scrubbing', price: 500 }],
      },
    ],
  },

  {
    category: 'Painting & Waterproofing', icon: '🎨', color: '#EDE9FE',
    services: [
      {
        name: 'Room Wall Painting',
        description: 'Interior wall painting of a single room including surface preparation, primer coat, and two finish coats.',
        variants: ['Single wall', 'Bedroom', 'Living room', 'Dining room', 'Kitchen', 'Bathroom'],
        priceRange: [2499, 6999],
        addons: [{ name: 'Premium emulsion upgrade', price: 1000 }, { name: 'Putty (wall levelling)', price: 800 }, { name: 'Texture / design finish', price: 1500 }],
      },
      {
        name: 'Full Apartment Painting',
        description: 'Complete interior painting of an entire apartment with all rooms, kitchen, and bathrooms.',
        variants: ['Furnished 1 BHK', 'Furnished 2 BHK', 'Furnished 3 BHK', 'Unfurnished 1 BHK', 'Unfurnished 2 BHK', 'Unfurnished 3 BHK'],
        priceRange: [9499, 20000],
        addons: [{ name: 'Balcony painting', price: 3499 }, { name: 'Premium paint upgrade', price: 2000 }, { name: 'False ceiling painting', price: 1500 }],
      },
      {
        name: 'Door & Wood Polish Painting',
        description: 'Painting or polishing wooden doors, frames, windows, grills, or metal gates with enamel or wood polish finish.',
        variants: ['Wooden door (enamel)', 'Metal gate / grill', 'Cabinet painting', 'Window frame painting'],
        priceRange: [1999, 3499],
        addons: [{ name: 'Sandpaper & prep work', price: 300 }, { name: 'Anti-rust primer for metal', price: 400 }],
      },
      {
        name: 'Exterior / Terrace Painting',
        description: 'Painting outer walls, balcony, or terrace parapet with weather-resistant exterior paint.',
        variants: ['Balcony walls', 'Terrace parapet', 'Exterior facade (per sq ft)'],
        priceRange: [1999, 8999],
        addons: [{ name: 'Scaffolding (if required)', price: 1500 }, { name: 'Weathershield paint upgrade', price: 1200 }],
      },
      {
        name: 'Wall Waterproofing',
        description: 'Applying waterproofing compound to seepage-prone walls, wet areas, or roof slabs to prevent water ingress and dampness.',
        variants: ['Single damp wall', 'Bathroom waterproofing', 'Terrace waterproofing', 'Exterior wall waterproofing'],
        priceRange: [2399, 7999],
        addons: [{ name: 'Crack filling', price: 500 }, { name: 'Anti-fungal treatment', price: 600 }],
      },
      {
        name: 'Tile Grouting & Gap Sealing',
        description: 'Refilling deteriorated or cracked tile grout in bathrooms, kitchens, or floors to prevent water seepage and improve appearance.',
        variants: ['Bathroom floor & walls', 'Kitchen backsplash', 'Floor tiles (per sq ft)'],
        priceRange: [1499, 3999],
        addons: [{ name: 'Anti-fungal grout', price: 400 }, { name: 'Silicone sealant for edges', price: 300 }],
      },
    ],
  },

  {
    category: 'Pest Control', icon: '🪲', color: '#FFF7ED',
    services: [
      {
        name: 'General Pest Control',
        description: 'Comprehensive treatment for common household pests including cockroaches, ants, silverfish, lizards, and spiders.',
        variants: ['1 BHK', '2 BHK', '3 BHK', '4 BHK', 'Villa / duplex'],
        priceRange: [699, 2499],
        addons: [{ name: 'Cockroach gel bait (extra)', price: 300 }, { name: 'Bed bug spot treatment', price: 600 }],
      },
      {
        name: 'Cockroach Control Treatment',
        description: 'Targeted gel bait treatment for cockroach infestations in kitchen, bathrooms, and utility areas with 3-month guarantee.',
        variants: ['Kitchen only', '1 BHK', '2 BHK', '3 BHK'],
        priceRange: [499, 1499],
        addons: [{ name: 'Second application (follow-up)', price: 399 }, { name: 'Anti-roach spray', price: 200 }],
      },
      {
        name: 'Bed Bug Treatment',
        description: 'Steam and chemical treatment for bed bug infestations in mattresses, bed frames, sofas, and upholstered furniture.',
        variants: ['1 bedroom', '2 bedrooms', 'Sofa treatment only'],
        priceRange: [1199, 3999],
        addons: [{ name: 'Second treatment (14-day follow-up)', price: 999 }, { name: 'Mattress encasement', price: 600 }],
      },
      {
        name: 'Termite Control',
        description: 'Chemical barrier or baiting system treatment to eliminate termite colonies and protect wooden structures.',
        variants: ['Post-construction (per room)', 'Pre-construction soil treatment', 'Spot treatment'],
        priceRange: [1499, 6999],
        addons: [{ name: 'Soil treatment per sq ft', price: 15 }, { name: 'Warranty certificate', price: 500 }, { name: 'Annual re-treatment', price: 2000 }],
      },
      {
        name: 'Rodent Control',
        description: 'Trapping, baiting, and entry-point sealing to eliminate rats and mice from home or office premises.',
        variants: ['Glue trap setup', 'Bait station (3 months)', 'Entry sealing + baiting combo'],
        priceRange: [899, 2999],
        addons: [{ name: 'Additional bait station', price: 400 }, { name: 'Sanitisation after rodent removal', price: 600 }],
      },
      {
        name: 'Mosquito Control',
        description: 'Fogging or larvicidal treatment to control mosquito populations around the home, garden, and water storage areas.',
        variants: ['Indoor fogging', 'Outdoor / garden fogging', 'Larvicidal treatment for water bodies'],
        priceRange: [699, 1999],
        addons: [{ name: 'Monthly maintenance plan (3 months)', price: 1500 }],
      },
    ],
  },

  {
    category: "Women's Salon & Beauty", icon: '💅', color: '#FDF4FF',
    services: [
      {
        name: 'Waxing',
        description: 'Smooth and efficient hair removal using spatula, roll-on, or RICA wax on arms, legs, underarms, or full body.',
        variants: ['Full arms & underarms', 'Full legs', 'Full arms, legs & underarms', 'Full body', 'Stomach', 'Back', 'Bikini line', 'RICA Brazilian'],
        priceRange: [99, 2499],
        addons: [{ name: 'RICA upgrade', price: 200 }, { name: 'Soothing aloe gel', price: 100 }],
      },
      {
        name: 'Threading & Eyebrow Shaping',
        description: 'Precise eyebrow threading, upper lip, chin, or forehead hair removal with expert shaping.',
        variants: ['Eyebrows only', 'Upper lip only', 'Eyebrows + upper lip + chin', 'Full face threading'],
        priceRange: [29, 199],
        addons: [{ name: 'Eyebrow tinting', price: 150 }, { name: 'Eyebrow serum', price: 100 }],
      },
      {
        name: 'Facial Treatment',
        description: 'Cleansing, exfoliating, and nourishing facial treatments targeting glowing skin, tan removal, hydration, or anti-ageing.',
        variants: ['Basic cleanup', 'Aroma Magic glow facial', 'Korean Glass hydration facial', 'O3+ shine & glow', 'Kumkumadi hydration facial', 'Ashwagandha tan removal', 'Firming Wine facial'],
        priceRange: [499, 1849],
        addons: [{ name: 'Under-eye treatment', price: 150 }, { name: 'Neck & décolletage mask', price: 200 }],
      },
      {
        name: 'Pedicure',
        description: 'Foot care treatment including soak, scrub, callus removal, cuticle care, nail shaping, and polish.',
        variants: ['Basic pedicure', 'Crystal Rose pedicure', 'Candle Spa pedicure', 'Foot massage (10 min add-on)'],
        priceRange: [249, 1419],
        addons: [{ name: 'Nail art (per nail)', price: 50 }, { name: 'Paraffin wax treatment', price: 300 }],
      },
      {
        name: 'Manicure',
        description: 'Hand care treatment with soak, exfoliation, cuticle care, nail shaping, buffing, and finish coat.',
        variants: ['Basic manicure', 'British Rose manicure', 'Candle Spa manicure', 'Cut, file & polish only'],
        priceRange: [249, 1189],
        addons: [{ name: 'Gel nail extension', price: 800 }, { name: 'Nail art', price: 50 }],
      },
      {
        name: "Women's Haircut & Styling",
        description: 'Expert haircut, blow-dry, or styling services at home by trained female professionals.',
        variants: ['Haircut (basic)', 'Haircut + blow-dry', 'Blow-dry & styling', 'Hair ironing / straightening'],
        priceRange: [349, 999],
        addons: [{ name: 'Hair serum treatment', price: 200 }, { name: 'Scalp massage', price: 150 }],
      },
      {
        name: 'Hair Spa & Treatment',
        description: 'Deep conditioning hair spa, keratin treatment, or protein treatment to restore shine, reduce frizz, and strengthen hair.',
        variants: ['Hair spa (deep conditioning)', 'Keratin treatment', 'Protein hair mask', 'Scalp detox treatment'],
        priceRange: [599, 2499],
        addons: [{ name: 'Steam treatment', price: 200 }, { name: 'Amla oil massage', price: 150 }],
      },
      {
        name: 'Hair Colour & Highlights',
        description: 'Application of hair colour, root touch-up, global highlights, or natural henna on hair (application only, colour not included).',
        variants: ['Root touch-up only', 'Global colour application', 'Highlights / balayage', 'Natural mehendi application'],
        priceRange: [399, 1999],
        addons: [{ name: 'Toning treatment', price: 400 }, { name: 'Shine serum', price: 200 }],
      },
      {
        name: 'Bleach & Detan',
        description: 'Skin lightening bleach or detan treatment to reduce tan lines, even skin tone, and brighten face, arms, or back.',
        variants: ['Face bleach', 'Arms bleach / detan', 'Back bleach', 'Full detan (face + arms + legs)'],
        priceRange: [449, 999],
        addons: [{ name: 'Brightening mask', price: 200 }, { name: 'SPF sunscreen application', price: 100 }],
      },
      {
        name: 'Pre-Bridal & Event Makeup',
        description: 'Professional event or bridal makeup at home including base, contouring, eye makeup, and setting for parties or weddings.',
        variants: ['Party makeup', 'Bridal glow package', 'Engagement look', 'Mehendi ceremony makeup'],
        priceRange: [1999, 6999],
        addons: [{ name: 'False lashes', price: 300 }, { name: 'HD foundation upgrade', price: 400 }, { name: 'Hair styling', price: 599 }, { name: 'Saree draping', price: 499 }],
      },
      {
        name: 'Mehendi / Henna Application',
        description: 'Intricate or bridal mehendi (henna) design application on hands, feet, or arms for weddings and festivities.',
        variants: ['Simple hands (both)', 'Bridal hands & feet', 'Arabic pattern (per hand)', 'Feet only'],
        priceRange: [299, 3999],
        addons: [{ name: 'Back design', price: 500 }, { name: 'Express drying oil', price: 100 }],
      },
    ],
  },

  {
    category: "Men's Salon & Grooming", icon: '💈', color: '#ECFDF5',
    services: [
      {
        name: "Men's Haircut",
        description: 'Professional haircut for men at home including wash, cut, and basic blow-dry by a trained male grooming expert.',
        variants: ['Regular haircut', 'Fade / undercut', 'Hair wash + cut + style', 'Kids haircut (under 12)'],
        priceRange: [199, 599],
        addons: [{ name: 'Hair styling product', price: 100 }, { name: 'Scalp massage', price: 100 }],
      },
      {
        name: 'Beard Trim & Styling',
        description: 'Expert beard trimming, shaping, and styling using trimmers and razor for a clean, defined look.',
        variants: ['Basic beard trim', 'Beard shaping & line-up', 'Clean shave (foam + razor)', 'Beard + moustache styling'],
        priceRange: [99, 399],
        addons: [{ name: 'Beard serum / oil treatment', price: 100 }, { name: 'Hot towel treatment', price: 80 }],
      },
      {
        name: 'Hair & Beard Colour',
        description: 'Application of hair colour, beard colour, or natural henna for men to cover grey hair.',
        variants: ['Hair colour (global)', 'Root touch-up only', 'Beard colour', 'Natural henna application'],
        priceRange: [299, 999],
        addons: [{ name: 'Anti-allergy patch test', price: 0 }, { name: 'Colour lock shampoo', price: 150 }],
      },
      {
        name: "Men's Facial & Skin Treatment",
        description: 'Deep cleansing, de-tan, or brightening facial for men targeting acne, dullness, oiliness, or tan.',
        variants: ['Men\'s basic cleanup', 'De-tan facial', 'Anti-acne treatment', 'Brightening facial'],
        priceRange: [399, 999],
        addons: [{ name: 'Blackhead extraction', price: 150 }, { name: 'Face serum', price: 150 }],
      },
      {
        name: "Men's Waxing",
        description: 'Hair removal waxing for men on chest, back, arms, or legs using hot or cold wax.',
        variants: ['Chest', 'Back', 'Full arms', 'Full legs', 'Underarms'],
        priceRange: [199, 999],
        addons: [{ name: 'Soothing post-wax lotion', price: 100 }],
      },
      {
        name: 'Head Massage & Scalp Treatment',
        description: 'Relaxing head massage with warm oil or ayurvedic oils targeting scalp health, dandruff, and hair fall.',
        variants: ['Basic head massage (15 min)', 'Oil massage (30 min)', 'Dandruff treatment', 'Anti-hair-fall scalp treatment'],
        priceRange: [249, 799],
        addons: [{ name: 'Steam hood treatment', price: 200 }, { name: 'Protein hair mask', price: 300 }],
      },
    ],
  },

  {
    category: 'Spa & Massage', icon: '🧖', color: '#F0F9FF',
    services: [
      {
        name: "Women's Spa — Swedish Massage",
        description: 'Full-body relaxation massage using long gliding strokes to release muscle tension, stress, and fatigue.',
        variants: ['45-minute session', '60-minute session', '90-minute session', '4-session package'],
        priceRange: [929, 2999],
        addons: [{ name: 'Aromatherapy oil upgrade', price: 200 }, { name: 'Hot stone add-on', price: 400 }],
      },
      {
        name: "Women's Spa — Deep Tissue Massage",
        description: 'Therapeutic massage targeting deep muscle layers for chronic pain, stiffness, or sports recovery using firm pressure.',
        variants: ['60-minute session', '90-minute session', '4-session package'],
        priceRange: [1199, 3499],
        addons: [{ name: 'Cupping therapy', price: 500 }, { name: 'Heated pad application', price: 200 }],
      },
      {
        name: "Women's Spa — Leg & Foot Relief",
        description: 'Targeted massage for tired, aching legs and feet including reflexology pressure points and calf muscle relief.',
        variants: ['Leg relief massage (30 min)', 'Foot reflexology (30 min)', 'Legs + feet combined (45 min)'],
        priceRange: [569, 999],
        addons: [{ name: 'Peppermint cooling gel', price: 100 }],
      },
      {
        name: "Men's Massage — Back & Shoulder",
        description: 'Targeted massage for upper back, neck, and shoulder pain from desk work, poor posture, or sports activity.',
        variants: ['Head, neck & shoulder (30 min)', 'Back relief massage (45 min)', 'Full upper body (60 min)'],
        priceRange: [669, 1299],
        addons: [{ name: 'Pain relief balm', price: 150 }, { name: 'Hot stone therapy', price: 300 }],
      },
      {
        name: "Men's Massage — Full Body",
        description: 'Complete full-body relaxation or therapeutic massage for men performed by a trained male therapist.',
        variants: ['Relaxation full body (60 min)', 'Therapeutic deep tissue (60 min)', '90-minute session'],
        priceRange: [919, 2499],
        addons: [{ name: 'Aromatherapy upgrade', price: 200 }, { name: 'Ayurvedic oil blend', price: 250 }],
      },
      {
        name: 'Foot Massage',
        description: 'Quick reflexology-based foot massage to relieve pressure, improve circulation, and reduce swelling.',
        variants: ['10-minute session', '20-minute session', '30-minute session'],
        priceRange: [249, 569],
        addons: [{ name: 'Foot scrub', price: 150 }, { name: 'Moisturising paraffin wax', price: 200 }],
      },
    ],
  },
];

export const CHIPS = [
  { label: 'Water pooling under sink', text: 'Water is pooling under my kitchen sink — there is a puddle on the floor every morning' },
  { label: 'AC running but not cooling', text: 'My AC runs all day but the room will not get cold at all, it is blowing warm air' },
  { label: 'Dull skin, wedding Saturday', text: 'My skin looks dull and tired. I have a wedding this Saturday and need to look glowing and fresh' },
  { label: 'Bathroom looks really bad', text: 'My bathroom looks really bad, not sure what it needs — could be cleaning or something else' },
  { label: 'Cockroaches in kitchen', text: 'I keep seeing cockroaches in my kitchen, especially at night near the sink and behind the fridge' },
  { label: 'Painting bedroom walls', text: 'I want to repaint my bedroom walls, they look old and have scuff marks everywhere' },
  { label: 'Wardrobe door stuck', text: 'My wardrobe door is jammed and will not open properly, the hinge seems broken' },
  { label: 'Geyser not heating', text: 'My geyser takes forever to heat water and sometimes gives only cold water even after 30 minutes' },
];
